import { afterEach, describe, expect, it, vi } from 'vitest'
import { cleanup, fireEvent, render, screen } from '@testing-library/react'

import { CreateSpacePanel } from '../../../../src/renderer/components/home/CreateSpacePanel'

function createBaseProps() {
  return {
    workspaceMode: 'managed' as const,
    provisioningMethod: 'copy-local' as const,
    // RepoPathPicker props (for copy-local and external)
    repoPath: '/Users/me/dev/kata-cloud',
    onRepoPathChange: vi.fn(),
    branches: ['main', 'develop'] as string[],
    selectedBranch: 'main',
    onBrowse: vi.fn(),
    onBranchChange: vi.fn(),
    isLoadingBranches: false,
    repoPathError: null as string | null,
    // GitHubRepoPicker props (for clone-github)
    githubRepos: [] as Array<{ name: string; nameWithOwner: string; url: string }>,
    selectedGithubRepo: null as { name: string; nameWithOwner: string; url: string } | null,
    onGithubRepoSelect: vi.fn(),
    isLoadingGithubRepos: false,
    githubSearchQuery: '',
    onGithubSearchChange: vi.fn(),
    githubBranches: [] as string[],
    selectedGithubBranch: '',
    onGithubBranchChange: vi.fn(),
    isLoadingGithubBranches: false,
    githubError: null as string | null,
    showGithubFallbackUrl: false,
    onGithubFallbackUrlChange: vi.fn(),
    // New repo props
    newRepoParentDir: '/Users/me/dev',
    newRepoFolderName: '',
    onNewRepoParentDirChange: vi.fn(),
    onNewRepoFolderNameChange: vi.fn(),
    // External workspace path
    workspacePath: '',
    onWorkspacePathChange: vi.fn(),
    // Review/create props
    autoGeneratedName: 'kata-cloud-x7k2',
    createError: null as string | null,
    canCreate: true,
    isCreating: false,
    summaryLines: ['Editable files: ~/.kata/workspaces/<id>/repo'],
    onSelectWorkspaceMode: vi.fn(),
    onSelectProvisioningMethod: vi.fn(),
    onCreateSpace: vi.fn()
  }
}

describe('CreateSpacePanel', () => {
  afterEach(() => {
    cleanup()
  })

  it('renders 3-step structure without old space name step', () => {
    render(<CreateSpacePanel {...createBaseProps()} />)

    expect(screen.getByText('Step 1 · Where work happens')).toBeTruthy()
    expect(screen.getByText('Step 2 · Source setup')).toBeTruthy()
    expect(screen.getByText('Step 3 · Review and create')).toBeTruthy()
    expect(screen.queryByText('Step 3 · Space name')).toBeNull()
    expect(screen.queryByText('Step 4 · Review and create')).toBeNull()
    expect(screen.queryByRole('textbox', { name: 'Space name' })).toBeNull()
  })

  it('shows RepoPathPicker for copy-local mode (browse button present)', () => {
    render(<CreateSpacePanel {...createBaseProps()} />)
    expect(screen.getByRole('button', { name: 'Browse' })).toBeTruthy()
  })

  it('shows RepoPathPicker for external mode', () => {
    render(<CreateSpacePanel {...createBaseProps()} workspaceMode="external" repoPath="/Users/me/repo" />)
    expect(screen.getByRole('button', { name: 'Browse' })).toBeTruthy()
  })

  it('shows GitHubRepoPicker for clone-github mode (search input present)', () => {
    render(<CreateSpacePanel {...createBaseProps()} provisioningMethod="clone-github" />)
    expect(screen.getByRole('textbox', { name: /search/i })).toBeTruthy()
  })

  it('shows new repo fields with correct labels', () => {
    render(<CreateSpacePanel {...createBaseProps()} provisioningMethod="new-repo" />)
    expect(screen.getByRole('textbox', { name: 'New repo parent directory' })).toBeTruthy()
    expect(screen.getByRole('textbox', { name: 'New repo name' })).toBeTruthy()
  })

  it('shows auto-generated name in review step', () => {
    render(<CreateSpacePanel {...createBaseProps()} />)
    expect(screen.getByText(/kata-cloud-x7k2/)).toBeTruthy()
  })

  it('shows managed source option buttons', () => {
    render(<CreateSpacePanel {...createBaseProps()} />)
    expect(screen.getByRole('button', { name: 'Use copy local provisioning' })).toBeTruthy()
    expect(screen.getByRole('button', { name: 'Use clone github provisioning' })).toBeTruthy()
    expect(screen.getByRole('button', { name: 'Use new repo provisioning' })).toBeTruthy()
  })

  it('disables create button when canCreate is false', () => {
    render(<CreateSpacePanel {...createBaseProps()} canCreate={false} />)
    expect(screen.getByRole('button', { name: 'Create space' })).toHaveProperty('disabled', true)
  })

  it('shows creating spinner', () => {
    render(<CreateSpacePanel {...createBaseProps()} isCreating={true} />)
    expect(screen.getByRole('button', { name: 'Create space' })).toHaveProperty('disabled', true)
    expect(screen.getByText('Creating space...')).toBeTruthy()
  })

  it('shows create error message', () => {
    render(<CreateSpacePanel {...createBaseProps()} createError="Boom" />)
    expect(screen.getByRole('alert').textContent).toContain('Boom')
  })

  it('wires workspace/provisioning selection and create handler', () => {
    const props = createBaseProps()
    render(<CreateSpacePanel {...props} />)

    fireEvent.click(screen.getByRole('button', { name: 'Use managed workspace' }))
    fireEvent.click(screen.getByRole('button', { name: 'Use my existing folder/worktree (developer-managed)' }))
    fireEvent.click(screen.getByRole('button', { name: 'Use copy local provisioning' }))
    fireEvent.click(screen.getByRole('button', { name: 'Use clone github provisioning' }))
    fireEvent.click(screen.getByRole('button', { name: 'Use new repo provisioning' }))
    fireEvent.click(screen.getByRole('button', { name: 'Create space' }))

    expect(props.onSelectWorkspaceMode).toHaveBeenCalledWith('managed')
    expect(props.onSelectWorkspaceMode).toHaveBeenCalledWith('external')
    expect(props.onSelectProvisioningMethod).toHaveBeenCalledWith('copy-local')
    expect(props.onSelectProvisioningMethod).toHaveBeenCalledWith('clone-github')
    expect(props.onSelectProvisioningMethod).toHaveBeenCalledWith('new-repo')
    expect(props.onCreateSpace).toHaveBeenCalledTimes(1)
  })

  it('wires new-repo field handlers', () => {
    const props = createBaseProps()
    render(<CreateSpacePanel {...props} provisioningMethod="new-repo" />)

    fireEvent.change(screen.getByRole('textbox', { name: 'New repo parent directory' }), {
      target: { value: '/Users/me/dev2' }
    })
    fireEvent.change(screen.getByRole('textbox', { name: 'New repo name' }), {
      target: { value: 'my-repo' }
    })

    expect(props.onNewRepoParentDirChange).toHaveBeenCalledWith('/Users/me/dev2')
    expect(props.onNewRepoFolderNameChange).toHaveBeenCalledWith('my-repo')
  })

  it('wires external workspace path handler', () => {
    const props = createBaseProps()
    render(<CreateSpacePanel {...props} workspaceMode="external" workspacePath="/Users/me/repo" />)

    // External mode still has a workspace path input for manual override
    fireEvent.change(screen.getByRole('textbox', { name: 'Workspace path' }), {
      target: { value: '/Users/me/worktrees/next' }
    })
    expect(props.onWorkspacePathChange).toHaveBeenCalledWith('/Users/me/worktrees/next')
  })
})
