import type { WorkspaceMode } from '@shared/types/space'

import { GitHubRepoPicker } from './GitHubRepoPicker'
import { RepoPathPicker } from './RepoPathPicker'

type ProvisioningMethod = 'copy-local' | 'clone-github' | 'new-repo'
type Repo = { name: string; nameWithOwner: string; url: string }

type CreateSpacePanelProps = {
  workspaceMode: WorkspaceMode
  provisioningMethod: ProvisioningMethod
  // RepoPathPicker props (for copy-local and external)
  repoPath: string
  branches: string[]
  selectedBranch: string
  onBrowse: () => void
  onBranchChange: (branch: string) => void
  isLoadingBranches: boolean
  repoPathError: string | null
  // GitHubRepoPicker props (for clone-github)
  githubRepos: Repo[]
  selectedGithubRepo: Repo | null
  onGithubRepoSelect: (repo: Repo) => void
  isLoadingGithubRepos: boolean
  githubSearchQuery: string
  onGithubSearchChange: (query: string) => void
  githubBranches: string[]
  selectedGithubBranch: string
  onGithubBranchChange: (branch: string) => void
  isLoadingGithubBranches: boolean
  githubError: string | null
  showGithubFallbackUrl: boolean
  onGithubFallbackUrlChange: (url: string) => void
  // New repo props
  newRepoParentDir: string
  newRepoFolderName: string
  onNewRepoParentDirChange: (value: string) => void
  onNewRepoFolderNameChange: (value: string) => void
  // External workspace path
  workspacePath: string
  onWorkspacePathChange: (value: string) => void
  // Review/create props
  autoGeneratedName: string
  createError: string | null
  canCreate: boolean
  isCreating: boolean
  summaryLines: string[]
  onSelectWorkspaceMode: (mode: WorkspaceMode) => void
  onSelectProvisioningMethod: (method: ProvisioningMethod) => void
  onCreateSpace: () => void
}

export function CreateSpacePanel({
  workspaceMode,
  provisioningMethod,
  repoPath,
  branches,
  selectedBranch,
  onBrowse,
  onBranchChange,
  isLoadingBranches,
  repoPathError,
  githubRepos,
  selectedGithubRepo,
  onGithubRepoSelect,
  isLoadingGithubRepos,
  githubSearchQuery,
  onGithubSearchChange,
  githubBranches,
  selectedGithubBranch,
  onGithubBranchChange,
  isLoadingGithubBranches,
  githubError,
  showGithubFallbackUrl,
  onGithubFallbackUrlChange,
  newRepoParentDir,
  newRepoFolderName,
  onNewRepoParentDirChange,
  onNewRepoFolderNameChange,
  workspacePath,
  onWorkspacePathChange,
  autoGeneratedName,
  createError,
  canCreate,
  isCreating,
  summaryLines,
  onSelectWorkspaceMode,
  onSelectProvisioningMethod,
  onCreateSpace
}: CreateSpacePanelProps) {
  return (
    <section
      data-testid="create-space-panel"
      className="rounded-2xl border border-border/80 bg-card/60 p-6 shadow-sm"
    >
      {/* Step 1: Where work happens */}
      <div className="rounded-lg border border-border/70 bg-background/60 p-3 text-xs text-muted-foreground">
        <p className="mb-1 font-medium text-foreground">Step 1 · Where work happens</p>
        <p className="mb-2 text-[11px] text-muted-foreground">
          Choose the editable workspace location before configuring any repository source settings.
        </p>
        <div className="grid gap-2 md:grid-cols-2">
          <button
            type="button"
            aria-label="Use managed workspace"
            aria-pressed={workspaceMode === 'managed'}
            onClick={() => onSelectWorkspaceMode('managed')}
            className="rounded-md border px-2 py-2 text-left text-xs aria-pressed:border-foreground aria-pressed:text-foreground"
          >
            Managed workspace (worktree)
          </button>
          <button
            type="button"
            aria-label="Use my existing folder/worktree (developer-managed)"
            aria-pressed={workspaceMode === 'external'}
            onClick={() => onSelectWorkspaceMode('external')}
            className="rounded-md border px-2 py-2 text-left text-xs aria-pressed:border-foreground aria-pressed:text-foreground"
          >
            Existing folder/worktree
          </button>
        </div>
      </div>

      {/* Step 2: Source setup */}
      <div className="mt-4 rounded-lg border border-border/70 bg-background/60 p-3 text-xs text-muted-foreground">
        <p className="mb-1 font-medium text-foreground">Step 2 · Source setup</p>
        {workspaceMode === 'managed' ? (
          <>
            <p className="mb-2 text-[11px] text-muted-foreground">
              Configure how the source repository is prepared before the managed worktree is created.
            </p>
            <div className="grid gap-2 md:grid-cols-3">
              <button
                type="button"
                aria-label="Use copy local provisioning"
                aria-pressed={provisioningMethod === 'copy-local'}
                onClick={() => onSelectProvisioningMethod('copy-local')}
                className="rounded-md border px-2 py-2 text-left text-xs aria-pressed:border-foreground aria-pressed:text-foreground"
              >
                Copy local repo
              </button>
              <button
                type="button"
                aria-label="Use clone github provisioning"
                aria-pressed={provisioningMethod === 'clone-github'}
                onClick={() => onSelectProvisioningMethod('clone-github')}
                className="rounded-md border px-2 py-2 text-left text-xs aria-pressed:border-foreground aria-pressed:text-foreground"
              >
                Clone from GitHub
              </button>
              <button
                type="button"
                aria-label="Use new repo provisioning"
                aria-pressed={provisioningMethod === 'new-repo'}
                onClick={() => onSelectProvisioningMethod('new-repo')}
                className="rounded-md border px-2 py-2 text-left text-xs aria-pressed:border-foreground aria-pressed:text-foreground"
              >
                Create new repo
              </button>
            </div>

            {provisioningMethod === 'copy-local' && (
              <RepoPathPicker
                path={repoPath}
                onBrowse={onBrowse}
                branches={branches}
                selectedBranch={selectedBranch}
                onBranchChange={onBranchChange}
                isLoadingBranches={isLoadingBranches}
                error={repoPathError}
              />
            )}

            {provisioningMethod === 'clone-github' && (
              <GitHubRepoPicker
                repos={githubRepos}
                selectedRepo={selectedGithubRepo}
                onRepoSelect={onGithubRepoSelect}
                isLoadingRepos={isLoadingGithubRepos}
                searchQuery={githubSearchQuery}
                onSearchChange={onGithubSearchChange}
                branches={githubBranches}
                selectedBranch={selectedGithubBranch}
                onBranchChange={onGithubBranchChange}
                isLoadingBranches={isLoadingGithubBranches}
                error={githubError}
                onFallbackUrlChange={onGithubFallbackUrlChange}
                showFallbackUrl={showGithubFallbackUrl}
              />
            )}

            {provisioningMethod === 'new-repo' && (
              <div className="mt-3 grid gap-2 md:grid-cols-2">
                <div>
                  <label className="mb-1 block text-xs text-foreground" htmlFor="new-repo-parent-input">
                    New repo parent directory
                  </label>
                  <input
                    id="new-repo-parent-input"
                    type="text"
                    aria-label="New repo parent directory"
                    value={newRepoParentDir}
                    onChange={(e) => onNewRepoParentDirChange(e.target.value)}
                    placeholder="/Users/you/dev"
                    className="h-8 w-full rounded-md border border-border bg-background/70 px-2 text-xs outline-none focus:border-ring"
                  />
                </div>
                <div>
                  <label className="mb-1 block text-xs text-foreground" htmlFor="new-repo-folder-input">
                    New repo name
                  </label>
                  <input
                    id="new-repo-folder-input"
                    type="text"
                    aria-label="New repo name"
                    value={newRepoFolderName}
                    onChange={(e) => onNewRepoFolderNameChange(e.target.value)}
                    placeholder="my-new-repo"
                    className="h-8 w-full rounded-md border border-border bg-background/70 px-2 text-xs outline-none focus:border-ring"
                  />
                </div>
              </div>
            )}
          </>
        ) : (
          <>
            <RepoPathPicker
              path={repoPath}
              onBrowse={onBrowse}
              branches={branches}
              selectedBranch={selectedBranch}
              onBranchChange={onBranchChange}
              isLoadingBranches={isLoadingBranches}
              error={repoPathError}
            />
            <div className="mt-2">
              <label className="mb-1 block text-xs text-foreground" htmlFor="workspace-path-input">
                Workspace path
              </label>
              <input
                id="workspace-path-input"
                type="text"
                aria-label="Workspace path"
                value={workspacePath}
                onChange={(e) => onWorkspacePathChange(e.target.value)}
                placeholder="/Users/you/dev/my-repo"
                className="h-8 w-full rounded-md border border-border bg-background/70 px-2 text-xs outline-none focus:border-ring"
              />
            </div>
          </>
        )}
      </div>

      {/* Step 3: Review and create */}
      <div className="mt-4 rounded-lg border border-border/70 bg-background/60 p-3 text-xs text-muted-foreground">
        <p className="mb-2 font-medium text-foreground">Step 3 · Review and create</p>
        <p className="mb-2 text-xs text-foreground">Space: {autoGeneratedName}</p>
        <ul className="space-y-1">
          {summaryLines.map((line) => (
            <li key={line} className="leading-relaxed text-[11px] text-muted-foreground">
              {line}
            </li>
          ))}
        </ul>
        {createError && (
          <p role="alert" className="mt-2 text-xs text-destructive">
            {createError}
          </p>
        )}
        <button
          type="button"
          aria-label="Create space"
          disabled={!canCreate || isCreating}
          className="mt-3 rounded-lg bg-emerald-600 px-3 py-1.5 text-xs font-semibold text-white hover:bg-emerald-500 disabled:cursor-not-allowed disabled:opacity-50"
          onClick={onCreateSpace}
        >
          {isCreating ? (
            <span className="inline-flex items-center gap-2">
              <span className="h-3 w-3 animate-spin rounded-full border-2 border-white/60 border-t-white" />
              Creating space...
            </span>
          ) : 'Create space'}
        </button>
      </div>
    </section>
  )
}
